// This file will be auto-generated by @tanstack/router-plugin
// Placeholder for initial build
import { Route as rootRoute } from './routes/__root';
import { Route as sidebarRoute } from './routes/_sidebar/route';
import { Route as indexRoute } from './routes/index';
import { Route as catalogBrowserRoute } from './routes/_sidebar/catalog-browser';
import { Route as enrichmentRoute } from './routes/_sidebar/enrichment';
import { Route as graphExplorerRoute } from './routes/_sidebar/graph-explorer';
import { Route as genieBuilderRoute } from './routes/_sidebar/genie-builder';
import { Route as genieCreateRoute } from './routes/_sidebar/genie-create';

export const routeTree = rootRoute.addChildren([
  indexRoute,
  sidebarRoute.addChildren([
    catalogBrowserRoute,
    enrichmentRoute,
    graphExplorerRoute,
    genieBuilderRoute,
    genieCreateRoute,
  ]),
]);
