/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidebarGraphExplorerRouteImport } from './routes/_sidebar/graph-explorer'
import { Route as SidebarGenieCreateRouteImport } from './routes/_sidebar/genie-create'
import { Route as SidebarGenieBuilderRouteImport } from './routes/_sidebar/genie-builder'
import { Route as SidebarEnrichmentRouteImport } from './routes/_sidebar/enrichment'
import { Route as SidebarCatalogBrowserRouteImport } from './routes/_sidebar/catalog-browser'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarGraphExplorerRoute = SidebarGraphExplorerRouteImport.update({
  id: '/graph-explorer',
  path: '/graph-explorer',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGenieCreateRoute = SidebarGenieCreateRouteImport.update({
  id: '/genie-create',
  path: '/genie-create',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGenieBuilderRoute = SidebarGenieBuilderRouteImport.update({
  id: '/genie-builder',
  path: '/genie-builder',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEnrichmentRoute = SidebarEnrichmentRouteImport.update({
  id: '/enrichment',
  path: '/enrichment',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCatalogBrowserRoute = SidebarCatalogBrowserRouteImport.update({
  id: '/catalog-browser',
  path: '/catalog-browser',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog-browser': typeof SidebarCatalogBrowserRoute
  '/enrichment': typeof SidebarEnrichmentRoute
  '/genie-builder': typeof SidebarGenieBuilderRoute
  '/genie-create': typeof SidebarGenieCreateRoute
  '/graph-explorer': typeof SidebarGraphExplorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog-browser': typeof SidebarCatalogBrowserRoute
  '/enrichment': typeof SidebarEnrichmentRoute
  '/genie-builder': typeof SidebarGenieBuilderRoute
  '/genie-create': typeof SidebarGenieCreateRoute
  '/graph-explorer': typeof SidebarGraphExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/catalog-browser': typeof SidebarCatalogBrowserRoute
  '/_sidebar/enrichment': typeof SidebarEnrichmentRoute
  '/_sidebar/genie-builder': typeof SidebarGenieBuilderRoute
  '/_sidebar/genie-create': typeof SidebarGenieCreateRoute
  '/_sidebar/graph-explorer': typeof SidebarGraphExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog-browser'
    | '/enrichment'
    | '/genie-builder'
    | '/genie-create'
    | '/graph-explorer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog-browser'
    | '/enrichment'
    | '/genie-builder'
    | '/genie-create'
    | '/graph-explorer'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/catalog-browser'
    | '/_sidebar/enrichment'
    | '/_sidebar/genie-builder'
    | '/_sidebar/genie-create'
    | '/_sidebar/graph-explorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/graph-explorer': {
      id: '/_sidebar/graph-explorer'
      path: '/graph-explorer'
      fullPath: '/graph-explorer'
      preLoaderRoute: typeof SidebarGraphExplorerRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/genie-create': {
      id: '/_sidebar/genie-create'
      path: '/genie-create'
      fullPath: '/genie-create'
      preLoaderRoute: typeof SidebarGenieCreateRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/genie-builder': {
      id: '/_sidebar/genie-builder'
      path: '/genie-builder'
      fullPath: '/genie-builder'
      preLoaderRoute: typeof SidebarGenieBuilderRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/enrichment': {
      id: '/_sidebar/enrichment'
      path: '/enrichment'
      fullPath: '/enrichment'
      preLoaderRoute: typeof SidebarEnrichmentRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/catalog-browser': {
      id: '/_sidebar/catalog-browser'
      path: '/catalog-browser'
      fullPath: '/catalog-browser'
      preLoaderRoute: typeof SidebarCatalogBrowserRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarCatalogBrowserRoute: typeof SidebarCatalogBrowserRoute
  SidebarEnrichmentRoute: typeof SidebarEnrichmentRoute
  SidebarGenieBuilderRoute: typeof SidebarGenieBuilderRoute
  SidebarGenieCreateRoute: typeof SidebarGenieCreateRoute
  SidebarGraphExplorerRoute: typeof SidebarGraphExplorerRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarCatalogBrowserRoute: SidebarCatalogBrowserRoute,
  SidebarEnrichmentRoute: SidebarEnrichmentRoute,
  SidebarGenieBuilderRoute: SidebarGenieBuilderRoute,
  SidebarGenieCreateRoute: SidebarGenieCreateRoute,
  SidebarGraphExplorerRoute: SidebarGraphExplorerRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
