# Databricks notebook source
# DBTITLE 1,hardcoded table_name
# # Define fully qualified table identifiers
# catalog_name = "dataroom_eval_bird"
# schema_name = "california_schools"
# table_name = "frpm"

# # Retrieve detailed table description (includes columns, data types, comments, etc.)
# df_description = spark.sql(
#     f"DESCRIBE EXTENDED {catalog_name}.{schema_name}.{table_name}"
# )
# # Display the metadata
# display(df_description)

# COMMAND ----------

import json
import pandas as pd
import os

# COMMAND ----------

#: Databricks notebook widgets for parameterization
# catalog/schema/table refers to source table.

dbutils.widgets.removeAll()

dbutils.widgets.text("catalog_name", os.getenv("ETL_CATALOG_NAME", "yyang"))
dbutils.widgets.text("schema_name", os.getenv("ETL_SCHEMA_NAME", "csv_health"))
dbutils.widgets.text("table_name", os.getenv("ETL_SOURCE_TABLE_NAME", "genie_example_data_apc"))
dbutils.widgets.text("destination_table_suffix", os.getenv("ETL_DESTINATION_TABLE_SUFFIX", "_ai_comment"))

catalog_name = dbutils.widgets.get("catalog_name")
schema_name = dbutils.widgets.get("schema_name")
table_name = dbutils.widgets.get("table_name")
destination_table_suffix = dbutils.widgets.get("destination_table_suffix")

# Construct the destination table name
destination_table = f"{table_name}{destination_table_suffix}"

# Retrieve detailed table description (includes columns, data types, comments, etc.)
df_description = spark.sql(
    f"DESCRIBE EXTENDED {catalog_name}.{schema_name}.{table_name}"
)
# Display the metadata
display(df_description)

# COMMAND ----------

# I dont need rows including col_name in ( '# Delta Statistics Columns', 'Column Names', 'Column Selection Method', 'Created Time', 'Last Access', 'Created By', 'Statistics', 'Type', 'Location', Provider, Owner, Is_managed_location, Predictive Optimization, Table Properties, NULL)

# # Preview the DESCRIBE EXTENDED output (optional, for debugging)
# display(df_description.limit(20))

# Keep only rows where data_type is not null and col_name does not start with '#'
from pyspark.sql.functions import col

# Implement a robust filter for df_description to keep only real columns and you can also manually append the colnames you want to skip.
df_description_clean = df_description.filter(
    (col('data_type').isNotNull()) & (~col('col_name').startswith('#')) & (col('col_name') != '') & (~col('col_name').isin(
    '# Delta Statistics Columns', 'Column Names', 'Column Selection Method', 'Created Time', 'Last Access', 'Created By', 'Statistics', 'Type', 'Location', 'Provider', 'Owner', 'Is_managed_location', 'Predictive Optimization', 'Table Properties')))

display(df_description_clean)

# COMMAND ----------

# 1. Collect column metadata
columns = df_description_clean.select('col_name', 'data_type', 'comment').toPandas().to_dict('records')

# COMMAND ----------

prompt = (
    "You will receive a list of columns in JSON: "
    + json.dumps(columns)
    + "\n Use all these information to improve the 'comment' of a single entry, e.g., for {\"col_name\": \"CDSCode\", \"data_type\": \"string\", \"comment\": \"CDSCode\"}, improve the field {\"comment\": \"CDSCode\"} to be {\"comment\": \"A CDS (County-District-School) code is a unique 14-digit identification number assigned to each school within California by the California Department of Education (CDE) for tracking and administrative purposes related to funding, assessments, and grants. \"}. Return the JSON object with exactly the same format as before, just add another field 'updated_comment' for each entry's improved comment generated by you. Only return the JSON object in your answer. Dont add any explanations and thoughts."
)

# COMMAND ----------

prompt

# COMMAND ----------

# Get LLM endpoint from environment variable
llm_endpoint = os.getenv("ETL_LLM_ENDPOINT", "databricks-llama-4-maverick")
llm_result = spark.sql(f"SELECT ai_query('{llm_endpoint}', ? ) as result", [prompt]).collect()[0]['result']

# COMMAND ----------

display(llm_result)

# COMMAND ----------

llm_result_str = llm_result.replace('```json', '').replace('```','') 

# COMMAND ----------

print(llm_result_str)

# COMMAND ----------

import json
col2comment = json.loads(llm_result_str)

# COMMAND ----------

df_table_with_comment = spark.createDataFrame(col2comment)

# COMMAND ----------

df_table_with_comment.display()

# COMMAND ----------

# Construct the fully qualified destination table name
destination_table_name = f"{catalog_name}.{schema_name}.{destination_table}"
df_table_with_comment.write.mode("overwrite") \
                     .saveAsTable(destination_table_name)
